baseURL                 = 'https://wecamp.pro/'
canonifyurls            = "true"
languageCode            = 'fa-ir'
title                   = 'وی‌کمپ | یادگیری عمیق، فراتر از بوت‌کمپ'
publishDir              = "docs"

# Enable robots output in your config:
enableRobotsTXT = true

#[permalinks]
#    about-us             = "/:section/:contentbasename/"
#    blog                = "/:section/:year/:month/:title/"
#    apply                 = "/:section/:contentbasename/"
#    something_else                = "/:title/"

[[cascade]]
   [cascade._target]
    path = '/camps/coming-soon'
    [cascade.params]
      layout = "coming-soon"
#########################################
#                 Camps                 #
#########################################
####Product Design
[[cascade]]
   [cascade._target]
    path = '/camps/product-design'
    [cascade.params]
      layout = "product-design"
[[cascade]]
   [cascade._target]
    path = '/camps/product-design-advanced'
    [cascade.params]
      layout = "product-design-advanced"
[[cascade]]
   [cascade._target]
    path = '/camps/product-design-project'
    [cascade.params]
      layout = "product-design-project"
[[cascade]]
   [cascade._target]
    path = '/camps/user-research'
    [cascade.params]
      layout = "user-research"

####Cloud
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-infra-management'
    [cascade.params]
      layout = "cloud-infra-management"
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-infra-deployment'
    [cascade.params]
      layout = "cloud-infra-deployment"
[[cascade]]
   [cascade._target]
    path = '/camps/cloud-infra-deepdive'
    [cascade.params]
      layout = "cloud-infra-deepdive"

####AI
[[cascade]]
   [cascade._target]
    path = '/camps/agentic-ai'
    [cascade.params]
      layout = "agentic-ai"

########################################
#                 PATH                 #
###################AI###################
[[cascade]]
   [cascade._target]
    path = '/path/product-design'
    [cascade.params]
      layout = "product-design"

[[cascade]]
   [cascade._target]
    path = '/path/cloud-engineering'
    [cascade.params]
      layout = "cloud-engineering"

[[cascade]]
   [cascade._target]
    path = '/path/ai-engineering'
    [cascade.params]
      layout = "ai-engineering"


#########################################
#                Talents                #
###################AI####################
[[cascade]]
   [cascade._target]
    path = '/talents/firstname-lastname'
    [cascade.params]
      layout = "firstname-lastname"

#########################################
#                 Other                 #
###################AI####################
[[cascade]]
   [cascade._target]
    path = '/courses/cloud-infra-management'
    [cascade.params]
      layout = "cloud-infra-management"

[[cascade]]
   [cascade._target]
    path = '/events/ai'
    [cascade.params]
      layout = "ai"
